
rules:
  semi: [ 2, "always" ]
  no-cond-assign: [ 0 ]
  prefer-arrow-callback: 2
  prefer-const: 2
  no-var: 2
  strict: 2


env:
  es6: true
  browser: true
  mocha: true
  node: true

extends: "eslint:recommended"

parserOptions:
  sourceType: "module"
  ecmaVersion: 2018
